### ISSUE TITLE
Nuget Package

### ISSUE THREAD

**Issue by andreysaf** [smourier/DirectNAot#1]
First of all, thank you for all your work! I am building .NET 8 CLI app and was hoping to use your amazing library. I am just working with Media Foundation only. What would be the best way to add it to the project? I could not find it through Nuget.

**Comment by andreysaf** [comment]
Closing the issue -- as I was able to reference your samples in your repository. My apologies.

**Comment by smourier** [comment]
Hi,

Yes, there's no nuget yet as it's not yet 100% stable (so you must get the source and compile by yourself - which is quite long unfortunately because there's around 8000 files) but it's almost there :-)
