### ISSUE TITLE
32bit Support

### ISSUE THREAD

**Issue by slmyyy** [smourier/DirectNAot#5]
As of May 2020, Microsoft no longer provides 32bit builds of Windows.  You would be hard pressed to actually find a PC running 32bit Windows today.

For the sake of simplicity, I propose the removal of _32 and _64 suffixes and doing away with the _32 objects.  This change will literally impact nobody but will tidy DirectN and make usage easier.

**Comment by smourier** [comment]
Any 64bit Windows supports running 32bit processes, so it's not strictly related to the fact 32-bit Windows is gone.

Anyway, there shouldn't be any _32 or _64 files in DirectN AOT. There was some (manually defined) in DirectN but DirectN AOT focuses only on x64. And DirectN.dll AOT is 99% generated, so it's more work to remove things than to just keep them in there.
